# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QApplication, QMainWindow, QWidget

def search_Button():
    print("zbeub")

class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(792, 592)

        self.listWidget = QtWidgets.QListWidget(parent=Widget)
        self.listWidget.setGeometry(QtCore.QRect(10, 130, 771, 441))
        self.listWidget.setObjectName("listWidget")

        self.lineEdit = QtWidgets.QLineEdit(parent=Widget)
        self.lineEdit.setGeometry(QtCore.QRect(10, 10, 461, 21))
        self.lineEdit.setPlaceholderText("Search by anime...")
        self.lineEdit.setObjectName("lineEdit")

        self.lineEdit_2 = QtWidgets.QLineEdit(parent=Widget)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 40, 461, 21))
        self.lineEdit_2.setPlaceholderText("Search by song name...")
        self.lineEdit_2.setObjectName("lineEdit_2")

        self.lineEdit_3 = QtWidgets.QLineEdit(parent=Widget)
        self.lineEdit_3.setGeometry(QtCore.QRect(10, 70, 461, 21))
        self.lineEdit_3.setPlaceholderText("Search by artist...")
        self.lineEdit_3.setObjectName("lineEdit_3")

        self.lineEdit_4 = QtWidgets.QLineEdit(parent=Widget)
        self.lineEdit_4.setGeometry(QtCore.QRect(10, 100, 461, 21))
        self.lineEdit_4.setPlaceholderText("Search by composer...")
        self.lineEdit_4.setObjectName("lineEdit_4")

        self.checkBox = QtWidgets.QCheckBox(parent=Widget)
        self.checkBox.setGeometry(QtCore.QRect(480, 10, 101, 21))
        self.checkBox.setText("Partial Match")
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")

        self.checkBox_2 = QtWidgets.QCheckBox(parent=Widget)
        self.checkBox_2.setGeometry(QtCore.QRect(480, 40, 101, 21))
        self.checkBox_2.setText("Partial Match")
        self.checkBox_2.setChecked(True)
        self.checkBox_2.setObjectName("checkBox_2")

        self.checkBox_3 = QtWidgets.QCheckBox(parent=Widget)
        self.checkBox_3.setGeometry(QtCore.QRect(480, 70, 101, 21))
        self.checkBox_3.setText("Partial Match")
        self.checkBox_3.setChecked(True)
        self.checkBox_3.setObjectName("checkBox_3")

        self.checkBox_4 = QtWidgets.QCheckBox(parent=Widget)
        self.checkBox_4.setGeometry(QtCore.QRect(480, 100, 101, 21))
        self.checkBox_4.setText("Partial Match")
        self.checkBox_4.setChecked(True)
        self.checkBox_4.setObjectName("checkBox_4")

        self.pushButton = QtWidgets.QPushButton(parent=Widget)
        self.pushButton.setGeometry(QtCore.QRect(700, 10, 81, 25))
        self.pushButton.setText("Search")
        self.pushButton.setObjectName("pushButton")

        self.pushButton_2 = QtWidgets.QPushButton(parent=Widget)
        self.pushButton_2.setGeometry(QtCore.QRect(590, 40, 191, 25))
        self.pushButton_2.setText("Download selection (MP3)")
        self.pushButton_2.setObjectName("pushButton_2")

        self.pushButton_3 = QtWidgets.QPushButton(parent=Widget)
        self.pushButton_3.setGeometry(QtCore.QRect(590, 100, 191, 25))
        self.pushButton_3.setText("Download selection (SD)")
        self.pushButton_3.setObjectName("pushButton_3")

        self.pushButton_4 = QtWidgets.QPushButton(parent=Widget)
        self.pushButton_4.setGeometry(QtCore.QRect(590, 70, 191, 25))
        self.pushButton_4.setText("Download selection (HD)")
        self.pushButton_4.setObjectName("pushButton_4")

        self.comboBox = QtWidgets.QComboBox(parent=Widget)
        self.comboBox.setGeometry(QtCore.QRect(590, 10, 101, 25))
        self.comboBox.setEditable(False)
        self.comboBox.setCurrentText("")
        self.comboBox.setPlaceholderText("")
        self.comboBox.setObjectName("comboBox")

        QtCore.QMetaObject.connectSlotsByName(Widget)

class MainWindow(QMainWindow):

    def __init__(self):
        super(MainWindow, self).__init__()

        self.setWindowTitle("My App")
        self.setFixedSize(792,592)

app = QApplication([])

window = MainWindow()
Ui_Widget().setupUi(window)
window.show()

app.exec()
